// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Fyb9WRrlTwtLxTcS4cbiuXL01kYP4cM',
    appId: '1:703179355509:web:00f4c3b74ec85f23360f3c',
    messagingSenderId: '703179355509',
    projectId: 'arnab-portfolio-844d1',
    authDomain: 'arnab-portfolio-844d1.firebaseapp.com',
    storageBucket: 'arnab-portfolio-844d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK7fos3JaDDR0NPfgNj0-v9cgBhTZTVa8',
    appId: '1:703179355509:android:d0ecf850c8611a90360f3c',
    messagingSenderId: '703179355509',
    projectId: 'arnab-portfolio-844d1',
    storageBucket: 'arnab-portfolio-844d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD57zGLBlFnTFnVKfkuvlPZMCPSfTrqX7U',
    appId: '1:703179355509:ios:5976ae9fbfd46dba360f3c',
    messagingSenderId: '703179355509',
    projectId: 'arnab-portfolio-844d1',
    storageBucket: 'arnab-portfolio-844d1.firebasestorage.app',
    iosBundleId: 'com.example.protfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD57zGLBlFnTFnVKfkuvlPZMCPSfTrqX7U',
    appId: '1:703179355509:ios:5976ae9fbfd46dba360f3c',
    messagingSenderId: '703179355509',
    projectId: 'arnab-portfolio-844d1',
    storageBucket: 'arnab-portfolio-844d1.firebasestorage.app',
    iosBundleId: 'com.example.protfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Fyb9WRrlTwtLxTcS4cbiuXL01kYP4cM',
    appId: '1:703179355509:web:36d7c9672adb3599360f3c',
    messagingSenderId: '703179355509',
    projectId: 'arnab-portfolio-844d1',
    authDomain: 'arnab-portfolio-844d1.firebaseapp.com',
    storageBucket: 'arnab-portfolio-844d1.firebasestorage.app',
  );
}
